spring.application.name=vacaciones_db
spring.datasource.url=jdbc:postgresql://localhost:5432/vacaciones_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cesardavidpatinovera@gmail.com 
spring.mail.password=rzdtyvnltmzpnkcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.main.allow-circular-references=true

#clave secreta para token
jwt.secret=2iFBbtE1VvamHUKioDWTW2QudnXeoYJvs5lp+EDWiZKmGxWXnfamjDmnd2A9dtu9HQoTNHJBXb38kCsRez2dOg==

#url base
app.base-url=http://localhost:5173

#url para reset password
app.reset-password-url=http://localhost:5173/reset-password
app.reset-password-requires-change-url=/reset-password
#variables de expiracion para el token
jwt.expiration-reset-password=30
jwt.expiration-login=1440


# Ruta al archivo JSON de credenciales de la cuenta de servicio
google.drive.credentials.path=credentials.json

# ID de la carpeta principal en Google Drive
google.drive.folder.root=1OG1dzpcaYSTML6SfRnP0sOmQQsCy3MIe


